[package]
name = "prism_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12.1"
tokio = { version = "1.35.1", features = ["sync"] }
